sudo: false
language: csharp
solution: Metrics.NET.Prometheus.sln

mono:
 - latest

install:
 - nuget restore Metrics.NET.Prometheus.sln

script:
 - xbuild ./Metrics.NET.Prometheus.sln /p:Configuration="Debug" /nologo /verbosity:normal
 - xbuild ./Metrics.NET.Prometheus.sln /p:Configuration="Release" /nologo /verbosity:normal
