language: objective-c

branches:
  except:
    - net40
env:
 global:
  - EnableNuGetPackageRestore=true
 matrix:
  - MONO_VERSION="4.2.0.114"
before_install:
 - wget "http://download.mono-project.com/archive/4.2.0/macos-10-x86/MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg"
 - sudo installer -pkg "MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg" -target /

script:
 - mono .nuget/nuget.exe restore Metrics.NET.Prometheus.sln 
 - xbuild Metrics.NET.Prometheus.sln /p:Configuration="Debug"
 - xbuild Metrics.NET.Prometheus.sln /p:Configuration="Release"
